requirements: update Flask-HTTPAuth version
The `werkzeug.security.safe_str_cmp` previously used in Flask-HTTPAuth
has been removed from Werkzeug since version 2.1.0, which leads to an
error: "ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security'".
Let's update Flask-HTTPAuth.